chat:
  auto_reply: true
early_access: true
language: en
reviews:
  auto_review:
    enabled: true
  path_instructions:
    - instructions: When making a pull request to the main branch, please warn that the pre-release notation should be removed if the version is a pre-release.
      path: package.json
