enableGlobalVirtualStore: true
engineStrict: true
gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
onlyBuiltDependencies:
  - esbuild
packages:
  - packages/*
pmOnFail: warn
shellEmulator: true
# Prevent parallel execution of publish. Since no `--workspace-concurrency`
# option exists for pnpm publish, we're increasing the number from 1 as
# necessary.
workspaceConcurrency: 1
