concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
name: The CI workflow on push
on:
  push:
permissions:
  contents: read
run-name: Pushed by @${{ github.actor }}
jobs:
  build:
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    env:
      COREPACK_INTEGRITY_KEYS: 0
    name: The build process
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Stages the pushed branch
        uses: actions/checkout@v4
      - name: Pre-prepare the Node.js version ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the latest corepack explicitly
        run: npm install --force -g corepack@latest
      - name: Enable the corepack
        run: corepack enable
      - name: Post-prepare the Node.js version ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version: ${{ matrix.node-version }}
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm i --frozen-lockfile
      - name: Run the tests
        run: pnpm run test
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
          - 24.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: bash
          - os: windows-latest
            shell: powershell
      fail-fast: false
    timeout-minutes: 30
