name: Publish the packages as the alpha version
run-name: Publish by as the alpha version @${{ github.actor }}
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    uses: ./.github/workflows/common-release.yml
    with:
      next: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
